2025-02-19 10:55:22,190 - root - INFO - Base de datos de auditoría inicializada correctamente.
2025-02-19 10:58:28,542 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 10:58:28,544 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 10:59:07,904 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 10:59:07,905 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 11:02:23,293 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 11:02:23,293 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 11:03:31,557 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 11:03:31,558 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 11:04:27,825 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 11:04:27,825 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 11:07:47,443 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 11:07:47,443 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 11:09:14,011 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 11:09:14,013 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 11:10:25,341 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 11:10:25,341 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 11:39:08,737 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 11:39:08,738 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 11:51:27,464 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 11:51:27,464 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 13:02:14,532 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 13:02:14,533 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 13:04:24,785 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 13:04:24,786 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 13:09:50,864 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 13:09:50,865 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 13:10:38,515 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 13:10:38,516 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 13:21:04,744 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 13:21:04,745 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 13:21:26,892 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 13:21:26,892 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 13:21:29,096 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29e4d65c10>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 13:21:30,098 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29e4d5fa50>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 13:21:32,099 - root - ERROR - Error en intento 1 de 3: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29e4d5d550>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 13:21:37,101 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29e4da9e50>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 13:21:38,102 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29e4d70590>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 13:21:40,104 - root - ERROR - Error en intento 2 de 3: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29e4d73390>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 13:21:45,106 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29e4d71d90>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 13:21:46,107 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29e4d70510>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 13:21:48,108 - root - ERROR - Error en intento 3 de 3: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29e4da9dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 13:21:58,495 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 13:21:58,495 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 13:22:02,315 - root - WARNING - No se tienen privilegios de root para leer la MAC (puede fallar).
2025-02-19 13:22:02,324 - root - INFO - Interfaz cambiada a ens33 (MAC: 00:0c:29:ea:58:09)
2025-02-19 13:22:14,177 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbae152850>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 13:22:15,179 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbadb109d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 13:22:17,180 - root - ERROR - Error en intento 1 de 3: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbadb12bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 13:22:22,182 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbadb11c50>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 13:22:23,183 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbadb108d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 13:22:25,184 - root - ERROR - Error en intento 2 de 3: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbae152950>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 13:22:30,186 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbadb21010>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 13:22:31,187 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbadb23290>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 13:22:33,189 - root - ERROR - Error en intento 3 de 3: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbadb2d4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 14:33:16,717 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 14:33:16,720 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:11:11,286 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:11:11,288 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:11:13,265 - MetasploitWindow - ERROR - Error cargando módulos: 'MetasploitConnectionManager' object has no attribute 'list_exploits'
2025-02-19 16:11:25,330 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140205340713024 and this is thread id 140205222790848.
2025-02-19 16:11:26,918 - MetasploitWindow - ERROR - Error cargando módulos: 'MetasploitConnectionManager' object has no attribute 'list_exploits'
2025-02-19 16:11:26,964 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:11:31,972 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:11:36,980 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:11:41,987 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:11:46,993 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:11:52,002 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:11:57,025 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:12:02,037 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:12:07,051 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:12:12,057 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:12:16,165 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:12:17,062 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:12:18,542 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:12:22,068 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:12:27,075 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:12:32,084 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:16:47,567 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:16:47,568 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:16:52,490 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 16:16:52,494 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 16:16:52,498 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 16:16:52,501 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:17:02,596 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139802054332480 and this is thread id 139801936266944.
2025-02-19 16:17:05,355 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:17:05,356 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:17:05,827 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:17:10,835 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:17:15,841 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:17:18,402 - MetasploitWindow - ERROR - Error mostrando información del módulo: 'MetasploitConnectionManager' object has no attribute 'get_exploit_info'
Traceback (most recent call last):
  File "/home/percival/Desktop/VulnHunter/ui/windows/metasploit.py", line 532, in _show_module_info
    info = self.msf_manager.get_exploit_info(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetasploitConnectionManager' object has no attribute 'get_exploit_info'
2025-02-19 16:17:20,134 - MetasploitWindow - ERROR - Error mostrando información del módulo: 'MetasploitConnectionManager' object has no attribute 'get_exploit_info'
Traceback (most recent call last):
  File "/home/percival/Desktop/VulnHunter/ui/windows/metasploit.py", line 532, in _show_module_info
    info = self.msf_manager.get_exploit_info(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetasploitConnectionManager' object has no attribute 'get_exploit_info'
2025-02-19 16:17:20,849 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:17:21,940 - MetasploitWindow - ERROR - Error mostrando información del módulo: 'MetasploitConnectionManager' object has no attribute 'get_payload_info'
Traceback (most recent call last):
  File "/home/percival/Desktop/VulnHunter/ui/windows/metasploit.py", line 534, in _show_module_info
    info = self.msf_manager.get_payload_info(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetasploitConnectionManager' object has no attribute 'get_payload_info'
2025-02-19 16:17:23,965 - MetasploitWindow - ERROR - Error mostrando información del módulo: 'MetasploitConnectionManager' object has no attribute 'get_auxiliary_info'
Traceback (most recent call last):
  File "/home/percival/Desktop/VulnHunter/ui/windows/metasploit.py", line 536, in _show_module_info
    info = self.msf_manager.get_auxiliary_info(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetasploitConnectionManager' object has no attribute 'get_auxiliary_info'
2025-02-19 16:17:25,855 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:17:30,860 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:17:35,870 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:17:40,875 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:17:45,886 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:17:50,897 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:17:55,908 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:00,914 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:05,924 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:10,930 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:15,937 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:20,942 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:25,950 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:30,955 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:35,960 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:40,971 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:45,979 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:50,987 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:18:55,993 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:19:00,999 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:19:06,005 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:19:11,013 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:19:16,020 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-19 16:19:20,322 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:19:20,323 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:19:32,074 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 16:19:32,079 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 16:19:32,083 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 16:19:32,087 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:19:42,198 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:19:44,203 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:19:44,203 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:19:44,256 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:19:44,257 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:19:49,267 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:19:49,267 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:19:54,278 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:19:54,279 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:19:59,291 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:19:59,293 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:04,300 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:04,301 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:09,312 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:09,312 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:14,322 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:14,323 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:19,331 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:19,336 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:24,344 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:24,345 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:29,353 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:29,353 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:34,364 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:34,365 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:39,372 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:39,373 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:44,380 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:44,384 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:49,396 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:49,396 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:54,404 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:54,407 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:20:59,415 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:20:59,415 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:04,427 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:04,429 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:09,439 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:09,439 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:14,450 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:14,451 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:19,459 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:19,459 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:24,469 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:24,469 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:29,481 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:29,485 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:34,492 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:34,492 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:39,509 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:39,509 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:44,521 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:44,524 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:49,540 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:49,540 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:54,568 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:54,569 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:21:59,578 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:21:59,578 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:04,587 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:04,587 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:09,596 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:09,599 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:14,606 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:14,607 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:19,622 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:19,623 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:24,631 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:24,632 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:29,639 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:29,640 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:34,650 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:34,651 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:39,663 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:39,663 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:44,671 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:44,675 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:49,689 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:49,690 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:54,698 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:54,699 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:22:59,707 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:22:59,708 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:23:04,720 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:23:04,720 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:23:09,730 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:23:09,730 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:23:14,739 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:23:14,745 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:23:19,753 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:23:19,754 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:23:24,763 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:23:24,763 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:23:29,773 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:23:29,774 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:23:34,789 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:23:34,790 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:23:39,805 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140668512886848 and this is thread id 140668395587264.
2025-02-19 16:23:39,805 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:23:43,908 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:23:43,910 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:23:45,865 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 16:23:45,869 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 16:23:45,874 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 16:23:45,879 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:23:56,188 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140521652678720 and this is thread id 140521534129856.
2025-02-19 16:24:30,323 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:24:31,784 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:25:43,912 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140521652678720 and this is thread id 140521534129856.
2025-02-19 16:25:43,949 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:29:37,891 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:29:37,894 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:29:39,800 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 16:29:39,805 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 16:29:39,809 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 16:29:39,816 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:29:50,110 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:29:52,388 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:29:52,388 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:29:52,462 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:29:52,463 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:29:57,470 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:29:57,470 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:02,481 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:02,482 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:07,491 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:07,493 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:12,502 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:12,503 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:17,519 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:17,520 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:22,531 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:22,532 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:27,540 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:27,541 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:32,548 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:32,549 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:37,559 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:37,560 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:42,567 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:42,568 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:47,579 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:47,581 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:52,589 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:52,590 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:30:57,599 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:30:57,600 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:02,614 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:31:02,615 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:07,625 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:31:07,627 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:12,634 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:31:12,634 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:17,643 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:31:17,644 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:22,651 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:31:22,651 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:27,671 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:31:27,671 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:28,110 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:31:28,111 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:31:29,835 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 16:31:29,840 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 16:31:29,845 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 16:31:29,850 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:31:32,688 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:31:32,691 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:37,700 - root - ERROR - Error al guardar registro de auditoría: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805607927872 and this is thread id 139805488842432.
2025-02-19 16:31:37,701 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:40,825 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:31:40,825 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:31:40,879 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:45,892 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:50,905 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:31:55,918 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:00,940 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:05,954 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:10,970 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:16,000 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:21,034 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:26,059 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:31,076 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:36,096 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:41,110 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:46,132 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:32:47,373 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:32:47,375 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:32:49,163 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 16:32:49,166 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 16:32:49,170 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 16:32:49,173 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:33:00,307 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:33:00,307 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:33:00,368 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:33:56,815 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:33:56,815 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:33:58,502 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 16:33:58,509 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 16:33:58,512 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 16:33:58,515 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:34:09,626 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:34:09,627 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:34:09,661 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:35:32,081 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:37:13,579 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:37:13,579 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:37:15,119 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 16:37:15,123 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 16:37:15,126 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 16:37:15,129 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:37:25,831 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:37:25,831 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:37:25,867 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:37:30,883 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:37:35,901 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:37:40,916 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:37:45,929 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:37:50,946 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:37:55,957 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:00,971 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:05,990 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:11,010 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:16,027 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:21,037 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:26,054 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:31,075 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:36,088 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:41,110 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:46,140 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:51,154 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:38:56,182 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:01,199 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:05,371 - root - ERROR - Error obteniendo código fuente: name 'subprocess' is not defined
2025-02-19 16:39:06,212 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:11,229 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:16,242 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:21,257 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:26,283 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:31,301 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:34,889 - root - ERROR - Error obteniendo código fuente: name 'subprocess' is not defined
2025-02-19 16:39:36,317 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:41,331 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:46,345 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:51,358 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:39:56,381 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:40:01,394 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:40:06,414 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:40:11,434 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:40:16,451 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:40:20,481 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:40:20,481 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:41:12,205 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 16:41:12,209 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 16:41:12,212 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 16:41:12,215 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:41:23,218 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:41:23,218 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:41:23,257 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:41:28,274 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:41:38,465 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'edit payload/android/meterpreter/reverse_http; exit'' timed out after 10 seconds
2025-02-19 16:41:38,563 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:41:43,576 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:41:54,459 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'edit payload/apple_ios/aarch64/meterpreter_reverse_http; exit'' timed out after 10 seconds
2025-02-19 16:41:54,512 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:41:59,526 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:04,552 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:09,564 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:14,577 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:19,592 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:24,686 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:29,701 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:34,717 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:39,763 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:44,781 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:49,806 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:54,819 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:42:59,842 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:44:14,830 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 16:44:14,830 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 16:44:16,997 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 16:44:17,008 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 16:44:17,011 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 16:44:17,016 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:44:27,906 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 16:44:27,907 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 16:44:27,959 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:44:42,685 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/mips64/meterpreter_reverse_https; exit'' timed out after 10 seconds
2025-02-19 16:44:42,762 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:44:47,779 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:44:52,794 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:45:03,081 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/mips64/meterpreter_reverse_tcp; exit'' timed out after 10 seconds
2025-02-19 16:45:03,145 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:45:18,116 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/mips64/meterpreter_reverse_http; exit'' timed out after 10 seconds
2025-02-19 16:45:18,192 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:45:23,209 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:45:35,357 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/x64/pingback_reverse_tcp; exit'' timed out after 10 seconds
2025-02-19 16:45:35,428 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:45:40,442 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:45:45,459 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:45:50,475 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:46:02,309 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/tftp/mips64/meterpreter_reverse_tcp; exit'' timed out after 10 seconds
2025-02-19 16:46:02,479 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:46:07,495 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:46:12,507 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:46:22,683 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'edit payload/android/meterpreter/reverse_http; exit'' timed out after 10 seconds
2025-02-19 16:46:22,761 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:46:27,773 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:46:38,725 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/unix/python/meterpreter/reverse_http; exit'' timed out after 10 seconds
2025-02-19 16:46:38,832 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:46:43,849 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:46:48,870 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:46:53,890 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:46:58,902 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:47:12,255 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'edit payload/java/meterpreter/bind_tcp; exit'' timed out after 10 seconds
2025-02-19 16:47:12,318 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:47:17,332 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:47:22,358 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:47:27,370 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:47:32,388 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:47:37,410 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 16:47:57,629 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:13:17,616 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 17:13:17,617 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 17:13:28,574 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 17:13:28,578 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 17:13:28,581 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 17:13:28,585 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 17:13:41,297 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 17:13:41,298 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 17:13:41,343 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:13:53,767 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'use exploit/aix/rpc_cmsd_opcode21; info -d; exit'' timed out after 10 seconds
2025-02-19 17:14:03,850 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:14:08,865 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:14:13,884 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:14:18,903 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:14:23,917 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:14:28,935 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:14:40,977 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'use payload/android/meterpreter/reverse_http; info -d; exit'' timed out after 10 seconds
2025-02-19 17:14:51,038 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:14:56,049 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:15:01,060 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:15:06,088 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:15:11,106 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:15:16,118 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:15:21,130 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:15:26,149 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:15:31,160 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:15:42,864 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'use payload/android/meterpreter/reverse_https; info -d; exit'' timed out after 10 seconds
2025-02-19 17:15:52,949 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:15:57,962 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:16:02,976 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:16:07,989 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:16:22,887 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'use payload/cmd/linux/http/mips64/meterpreter_reverse_http; info -d; exit'' timed out after 10 seconds
2025-02-19 17:16:33,042 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:16:38,059 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:16:51,370 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'use payload/cmd/linux/http/mips64/meterpreter_reverse_https; info -d; exit'' timed out after 10 seconds
2025-02-19 17:17:01,449 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:17:06,461 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:17:11,482 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:17:16,514 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:17:21,531 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:17:35,257 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'use payload/bsd/x86/shell/reverse_tcp; info -d; exit'' timed out after 10 seconds
2025-02-19 17:17:44,716 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:17:49,727 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:17:54,737 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:17:59,748 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:04,765 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:09,781 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:14,800 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:19,815 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:24,826 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:29,838 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:34,849 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:39,865 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:44,877 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:49,897 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:54,909 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:18:59,923 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:19:04,933 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:19:09,945 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:19:14,961 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:19:17,179 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 17:19:17,180 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 17:19:19,020 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 17:19:19,025 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 17:19:19,030 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 17:19:19,038 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 17:19:30,204 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 17:19:30,205 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 17:19:30,261 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:19:35,275 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:19:40,286 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:19:45,298 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:19:50,314 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:19:55,334 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:20:00,354 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:20:05,370 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:20:10,383 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:20:15,399 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:20:20,410 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:20:25,428 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 17:20:39,904 - root - ERROR - Error en msfconsole: Command 'msfconsole -q -x 'use payload/cmd/unix/reverse; info -d; exit'' timed out after 10 seconds
2025-02-19 18:38:58,507 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 18:38:58,508 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 18:39:00,196 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 18:39:00,200 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 18:39:00,203 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 18:39:00,207 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 18:39:11,354 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 18:39:11,354 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 18:39:11,725 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:39:16,122 - MetasploitWindow - ERROR - Error mostrando información: 'MetasploitConnectionManager' object has no attribute 'get_module_info'
Traceback (most recent call last):
  File "/home/percival/Desktop/VulnHunter/ui/windows/metasploit.py", line 532, in _show_module_info
    info = self.msf_manager.get_module_info(module_type, module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetasploitConnectionManager' object has no attribute 'get_module_info'
2025-02-19 18:39:16,742 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:39:21,167 - MetasploitWindow - ERROR - Error mostrando información: 'MetasploitConnectionManager' object has no attribute 'get_module_info'
Traceback (most recent call last):
  File "/home/percival/Desktop/VulnHunter/ui/windows/metasploit.py", line 532, in _show_module_info
    info = self.msf_manager.get_module_info(module_type, module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetasploitConnectionManager' object has no attribute 'get_module_info'
2025-02-19 18:39:21,759 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:39:28,177 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 18:39:28,178 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 18:39:29,517 - root - ERROR - Error listando exploits: No hay conexión activa con Metasploit
2025-02-19 18:39:29,521 - root - ERROR - Error listando payloads: No hay conexión activa con Metasploit
2025-02-19 18:39:29,524 - root - ERROR - Error listando auxiliares: No hay conexión activa con Metasploit
2025-02-19 18:39:29,527 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 18:39:40,417 - MetasploitWindow - INFO - Módulos cargados exitosamente
2025-02-19 18:39:40,417 - MetasploitWindow - INFO - Reconexión exitosa con Metasploit
2025-02-19 18:39:40,469 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:39:45,485 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:39:50,507 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:39:50,920 - MetasploitWindow - ERROR - Error mostrando información: 'MetasploitConnectionManager' object has no attribute 'get_module_info'
Traceback (most recent call last):
  File "/home/percival/Desktop/VulnHunter/ui/windows/metasploit.py", line 532, in _show_module_info
    info = self.msf_manager.get_module_info(module_type, module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetasploitConnectionManager' object has no attribute 'get_module_info'
2025-02-19 18:39:55,523 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:00,538 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:05,558 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:10,571 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:15,585 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:20,599 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:25,631 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:30,642 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:31,536 - MetasploitWindow - ERROR - Error mostrando información: 'MetasploitConnectionManager' object has no attribute 'get_module_info'
Traceback (most recent call last):
  File "/home/percival/Desktop/VulnHunter/ui/windows/metasploit.py", line 532, in _show_module_info
    info = self.msf_manager.get_module_info(module_type, module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetasploitConnectionManager' object has no attribute 'get_module_info'
2025-02-19 18:40:35,663 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:39,428 - root - WARNING - No se tienen privilegios de root para leer la MAC (puede fallar).
2025-02-19 18:40:39,437 - root - INFO - Interfaz cambiada a ens33 (MAC: 00:0c:29:ea:58:09)
2025-02-19 18:40:40,687 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:45,708 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:50,719 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:40:53,406 - root - ERROR - No se pudo detectar la subred local: You must specify a valid interface name.. Usando fallback.
2025-02-19 18:40:55,050 - root - ERROR - No se pudo detectar la subred local: You must specify a valid interface name.. Usando fallback.
2025-02-19 18:40:55,750 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:41:00,787 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:41:01,625 - root - WARNING - No se tienen privilegios de root para leer la MAC (puede fallar).
2025-02-19 18:41:01,639 - root - INFO - Interfaz cambiada a ens33 (MAC: 00:0c:29:ea:58:09)
2025-02-19 18:41:05,804 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:41:10,963 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:41:15,978 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:41:21,007 - MetasploitWindow - INFO - Sesiones actualizadas: 0 activas
2025-02-19 18:50:51,035 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 18:50:51,036 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 18:51:38,684 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 18:51:38,684 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 18:54:51,572 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 18:54:51,573 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 18:55:08,351 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 18:55:08,351 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 18:56:43,646 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 18:56:43,646 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 18:56:45,252 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:45,253 - MetasploitManager - ERROR - Error listando exploits: No hay conexión con Metasploit
2025-02-19 18:56:45,253 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:45,254 - MetasploitManager - ERROR - Error listando payloads: No hay conexión con Metasploit
2025-02-19 18:56:45,258 - MetasploitManager - ERROR - Error listando módulos auxiliares: No hay conexión con Metasploit
2025-02-19 18:56:46,634 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:50,253 - MetasploitManager - ERROR - Error obteniendo sesiones: No hay conexión con Metasploit
2025-02-19 18:56:50,322 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:50,325 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:51,114 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:51,879 - MetasploitManager - ERROR - Error obteniendo sesiones: No hay conexión con Metasploit
2025-02-19 18:56:52,365 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:52,608 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:52,784 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:52,934 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:53,289 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:53,446 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:54,638 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:54,958 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:55,254 - MetasploitManager - ERROR - Error obteniendo sesiones: No hay conexión con Metasploit
2025-02-19 18:56:55,335 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:56:55,339 - root - ERROR - Error al conectar a Metasploit: 'MetasploitConnectionManager' object has no attribute 'connections'
2025-02-19 18:58:40,845 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 18:58:40,845 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 18:58:42,165 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558ff75c10>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:58:43,166 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558ff722d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:58:45,168 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558ffa0c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:58:45,343 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559003c550>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:58:46,343 - MetasploitManager - ERROR - Error listando exploits: No hay conexión con Metasploit
2025-02-19 18:58:46,343 - MetasploitManager - ERROR - Error listando payloads: No hay conexión con Metasploit
2025-02-19 18:58:46,343 - MetasploitManager - ERROR - Error listando módulos auxiliares: No hay conexión con Metasploit
2025-02-19 18:58:46,345 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559003f390>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:58:46,472 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe55f90>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:58:47,473 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe60250>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:58:48,346 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe54f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:58:49,475 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559003efd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:58:50,342 - MetasploitManager - ERROR - Error obteniendo sesiones: No hay conexión con Metasploit
2025-02-19 18:58:51,988 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe61a90>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:58:52,989 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55900331d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:58:54,489 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe608d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:58:54,991 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe54590>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:58:55,000 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe71390>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:58:55,490 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe73610>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:58:56,001 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe61cd0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:58:57,492 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559003de10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:58:58,003 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe54c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:58:58,008 - MetasploitManager - ERROR - Error obteniendo sesiones: No hay conexión con Metasploit
2025-02-19 18:58:59,258 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe7d4d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:59:00,259 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe7f750>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:59:02,261 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559003f010>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:59:02,265 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe73f90>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:59:03,016 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe61850>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:59:03,266 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe883d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:59:04,018 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe8a650>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:59:05,267 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe7ee10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:59:05,272 - MetasploitManager - ERROR - Error obteniendo sesiones: No hay conexión con Metasploit
2025-02-19 18:59:06,019 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe70990>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:59:08,062 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe71dd0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:59:09,063 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe60e10>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:59:11,026 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe56310>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:59:11,065 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe724d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:59:11,067 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe7c6d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:59:12,028 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe57690>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:59:12,068 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe57e90>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:59:14,029 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559003d8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:59:14,070 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe7f950>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:59:14,071 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe575d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:59:15,072 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe60410>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:59:17,074 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559003efd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:59:17,075 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558ff80b50>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:59:18,076 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5590032410>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:59:20,077 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe61050>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 18:59:20,083 - MetasploitManager - ERROR - Error obteniendo sesiones: No hay conexión con Metasploit
2025-02-19 18:59:20,086 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe704d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
2025-02-19 18:59:21,087 - retry.api - WARNING - HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559003c490>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
2025-02-19 18:59:23,088 - MetasploitManager - ERROR - Error conectando a Metasploit: HTTPConnectionPool(host='127.0.0.1', port=55553): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f558fe7f050>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-19 19:02:07,545 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 19:02:07,546 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 19:02:09,113 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 19:02:15,209 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:02:18,843 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:02:43,248 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 19:02:43,249 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 19:02:44,599 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 19:02:50,433 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:02:55,314 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 19:03:57,916 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 19:03:57,917 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 19:04:01,351 - MetasploitManager - INFO - Iniciando servicio msfrpcd...
2025-02-19 19:04:09,418 - MetasploitManager - INFO - Servicio msfrpcd iniciado correctamente
2025-02-19 19:04:29,421 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 19:04:29,422 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 19:06:27,456 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 19:06:27,457 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 19:06:28,755 - MetasploitManager - INFO - Iniciando servicio msfrpcd...
2025-02-19 19:06:36,797 - MetasploitManager - INFO - Servicio msfrpcd iniciado correctamente
2025-02-19 19:06:37,040 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 19:06:37,087 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 19:06:40,459 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:06:52,793 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 19:07:11,493 - MetasploitWindow - ERROR - Error mostrando información: can't invoke "grab" command: application has been destroyed
Traceback (most recent call last):
  File "/home/percival/Desktop/VulnHunter/ui/windows/metasploit.py", line 475, in _show_module_info
    messagebox.showerror("Error", "No se pudo obtener la información del módulo")
  File "/usr/lib/python3.11/tkinter/messagebox.py", line 98, in showerror
    return _show(title, message, ERROR, OK, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/messagebox.py", line 76, in _show
    res = Message(**options).show()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/commondialog.py", line 45, in show
    s = master.tk.call(self.command, *master._options(self.options))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: can't invoke "grab" command: application has been destroyed
2025-02-19 19:10:31,693 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 19:10:31,695 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 19:10:33,151 - MetasploitManager - INFO - Iniciando servicio msfrpcd...
2025-02-19 19:10:41,204 - MetasploitManager - INFO - Servicio msfrpcd iniciado correctamente
2025-02-19 19:10:41,420 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 19:10:44,798 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:10:55,939 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 19:11:57,518 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 19:11:57,519 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 19:12:00,948 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-19 19:12:00,965 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 19:12:03,682 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:12:09,105 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 19:22:27,213 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 19:22:27,213 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 19:22:30,806 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-19 19:22:31,010 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 19:22:36,264 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:43:45,173 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 19:43:45,174 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 19:43:48,747 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-19 19:43:48,796 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 19:43:52,206 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-19 19:43:55,761 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:43:58,965 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:44:18,207 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-19 19:50:59,119 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-19 19:52:29,906 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-19 19:52:32,243 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:54:57,595 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-19 19:55:00,873 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-19 19:57:38,471 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-19 19:58:16,516 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:59:35,132 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 19:59:37,717 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-19 20:00:32,514 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:00:34,302 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-19 20:13:09,863 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 20:13:09,864 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 20:13:13,109 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-19 20:13:13,117 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 20:13:34,251 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:14:23,412 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:14:25,858 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-19 20:19:50,693 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 20:19:50,693 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 20:19:53,811 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-19 20:19:53,819 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 20:19:57,153 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:19:57,283 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:19:58,157 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:20:00,702 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:20:01,591 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:20:02,297 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:20:02,482 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:20:02,974 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:20:03,118 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:20:09,009 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:20:09,155 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:20:09,308 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:20:09,693 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:20:14,349 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:20:14,664 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:20:14,821 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:20:14,975 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:20:15,328 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:20:15,480 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:20:15,613 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:21:15,779 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 20:21:15,779 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 20:21:19,705 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-19 20:21:19,711 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 20:21:21,518 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:21:21,668 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:21:22,016 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:21:22,180 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:21:25,561 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:21:25,710 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:21:25,851 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:21:26,429 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:22:49,433 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 20:22:49,434 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 20:22:53,916 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-19 20:22:53,925 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 20:22:55,843 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:22:56,481 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:05,725 - root - INFO - Configuración cargada desde config.yaml.
2025-02-19 20:35:05,725 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-19 20:35:09,391 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-19 20:35:09,401 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-19 20:35:10,604 - MetasploitWindow - DEBUG - Se encontraron 2484 exploits.
2025-02-19 20:35:10,916 - MetasploitWindow - DEBUG - Se encontraron 1458 payloads.
2025-02-19 20:35:11,021 - MetasploitWindow - DEBUG - Se encontraron 1279 auxiliares.
2025-02-19 20:35:11,236 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:11,242 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:11,244 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:12,046 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:12,054 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:12,056 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:12,555 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:12,563 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:12,565 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:13,033 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:13,043 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:13,044 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:13,515 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:13,522 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:13,523 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:14,024 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:14,030 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:14,032 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:14,677 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:14,686 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:14,688 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:15,282 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:15,289 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:15,292 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:16,403 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:16,404 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:16,410 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:17,269 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:17,271 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:17,277 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:18,333 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:18,335 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:18,337 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:18,895 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:18,897 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:18,898 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-19 20:35:21,296 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'list' object has no attribute 'info'
2025-02-19 20:35:21,297 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-19 20:35:21,299 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-20 18:43:46,002 - root - INFO - Configuración cargada desde config.yaml.
2025-02-20 18:43:46,003 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-20 18:44:05,497 - root - WARNING - No se tienen privilegios de root para leer la MAC (puede fallar).
2025-02-20 18:44:05,510 - root - INFO - Interfaz cambiada a ens33 (MAC: 00:0c:29:ea:58:09)
2025-02-20 18:44:07,001 - root - ERROR - Se requieren privilegios de root para cambiar la MAC.
2025-02-20 18:44:07,002 - root - INFO - Error al cambiar MAC: No se pudo cambiar la MAC
2025-02-20 18:44:09,111 - root - WARNING - No se tienen privilegios de root para leer la MAC (puede fallar).
2025-02-20 18:44:09,114 - root - INFO - Interfaz cambiada a ens33 (MAC: 00:0c:29:ea:58:09)
2025-02-20 18:44:11,396 - root - WARNING - No se tienen privilegios de root para leer la MAC (puede fallar).
2025-02-20 18:44:11,399 - root - INFO - Interfaz cambiada a ens33 (MAC: 00:0c:29:ea:58:09)
2025-02-21 18:28:57,826 - root - INFO - Configuración cargada desde config.yaml.
2025-02-21 18:28:57,827 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-21 18:28:59,572 - MetasploitManager - INFO - Iniciando servicio msfrpcd...
2025-02-21 18:29:01,614 - MetasploitManager - INFO - Ejecutando comando: msfrpcd -P abc123 -S -a 127.0.0.1 -p 55553
2025-02-21 18:29:07,630 - MetasploitManager - INFO - Servicio msfrpcd iniciado correctamente
2025-02-21 18:29:09,630 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-21 18:29:09,903 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-21 18:29:47,916 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'exploit'
2025-02-21 18:30:19,379 - root - INFO - Configuración cargada desde config.yaml.
2025-02-21 18:30:19,379 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-21 18:30:23,071 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-21 18:30:23,078 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-21 18:30:27,347 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-21 18:30:35,331 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-21 18:30:38,683 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-21 18:30:41,716 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-21 18:30:42,902 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-21 18:31:08,873 - root - INFO - Configuración cargada desde config.yaml.
2025-02-21 18:31:08,873 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-21 18:31:12,314 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-21 18:31:12,320 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-21 18:31:16,012 - MetasploitManager - ERROR - Error obteniendo código fuente: 'ModuleManager' object has no attribute 'source'
2025-02-21 18:36:45,052 - root - INFO - Configuración cargada desde config.yaml.
2025-02-21 18:36:45,052 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-21 18:36:48,676 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-21 18:36:48,683 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-21 18:37:02,945 - root - ERROR - Error al obtener información del módulo exploit/android/local/futex_requeue: 'ModuleManager' object has no attribute 'info'
2025-02-21 18:37:22,774 - root - ERROR - Error al obtener información del módulo payload/cmd/linux/http/mips64/meterpreter_reverse_https: 'ModuleManager' object has no attribute 'info'
2025-02-21 18:37:43,434 - root - INFO - Configuración cargada desde config.yaml.
2025-02-21 18:37:43,435 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-21 18:37:46,747 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-21 18:37:46,773 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-21 18:37:59,475 - root - ERROR - Error al obtener información del módulo exploit/android/browser/samsung_knox_smdm_url: 'ModuleManager' object has no attribute 'info'
2025-02-21 18:45:12,955 - root - INFO - Configuración cargada desde config.yaml.
2025-02-21 18:45:12,955 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-21 18:45:24,006 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-21 18:45:24,014 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-21 18:45:37,005 - MetasploitManager - DEBUG - Error usando msfconsole: Command 'msfconsole -q -x 'edit exploit/android/fileformat/adobe_reader_pdf_js_interface; exit'' timed out after 10 seconds
2025-02-21 18:45:37,250 - root - ERROR - Error al obtener información del módulo exploit/android/fileformat/adobe_reader_pdf_js_interface: 'ModuleManager' object has no attribute 'info'
2025-02-21 18:46:06,835 - MetasploitManager - DEBUG - Error usando msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/mips64/meterpreter_reverse_http; exit'' timed out after 10 seconds
2025-02-21 18:46:06,939 - root - ERROR - Error al obtener información del módulo payload/cmd/linux/http/mips64/meterpreter_reverse_http: 'ModuleManager' object has no attribute 'info'
2025-02-21 18:46:21,913 - MetasploitManager - DEBUG - Error usando msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/https/mips64/meterpreter_reverse_http; exit'' timed out after 10 seconds
2025-02-21 18:46:22,015 - root - ERROR - Error al obtener información del módulo payload/cmd/linux/https/mips64/meterpreter_reverse_http: 'ModuleManager' object has no attribute 'info'
2025-02-21 18:48:31,528 - root - INFO - Configuración cargada desde config.yaml.
2025-02-21 18:48:31,529 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-21 18:48:34,940 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-21 18:48:34,946 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-21 18:48:54,568 - MetasploitManager - DEBUG - Error usando msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/mips64/meterpreter_reverse_https; exit'' timed out after 10 seconds
2025-02-21 18:49:14,732 - root - ERROR - Error al obtener información del módulo payload/cmd/linux/http/mips64/meterpreter_reverse_https: 'ModuleManager' object has no attribute 'info'
2025-02-21 18:49:36,575 - MetasploitManager - DEBUG - Error usando msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/mips64/meterpreter_reverse_https; exit'' timed out after 10 seconds
2025-02-21 18:49:56,705 - root - ERROR - Error al obtener información del módulo payload/cmd/linux/http/mips64/meterpreter_reverse_https: 'ModuleManager' object has no attribute 'info'
2025-02-21 18:50:00,782 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-21 18:50:03,026 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-22 06:20:53,750 - root - INFO - Configuración cargada desde config.yaml.
2025-02-22 06:20:53,750 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 06:20:57,231 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-22 06:20:58,159 - MetasploitManager - ERROR - Error conectando a Metasploit: 'MsfRPC: Authentication failed'
2025-02-22 06:20:59,359 - MetasploitManager - ERROR - Error listando exploits: No hay conexión con Metasploit
2025-02-22 06:20:59,360 - MetasploitManager - ERROR - Error listando payloads: No hay conexión con Metasploit
2025-02-22 06:20:59,360 - MetasploitManager - ERROR - Error listando módulos auxiliares: No hay conexión con Metasploit
2025-02-22 06:21:01,955 - MetasploitManager - INFO - Iniciando servicio msfrpcd...
2025-02-22 06:21:03,977 - MetasploitManager - INFO - Ejecutando comando: msfrpcd -P abc123 -S -a 127.0.0.1 -p 55553
2025-02-22 06:21:07,986 - MetasploitManager - INFO - Servicio msfrpcd iniciado correctamente
2025-02-22 06:21:09,987 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-22 06:21:10,110 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-22 06:21:16,763 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-22 06:21:28,439 - MetasploitManager - DEBUG - Error usando msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/mips64/meterpreter_reverse_https; exit'' timed out after 10 seconds
2025-02-22 06:21:48,697 - root - ERROR - Error al obtener información del módulo payload/cmd/linux/http/mips64/meterpreter_reverse_https: 'ModuleManager' object has no attribute 'info'
2025-02-22 06:21:56,113 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-22 06:22:07,532 - MetasploitManager - DEBUG - Error usando msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/mips64/meterpreter_reverse_tcp; exit'' timed out after 10 seconds
2025-02-22 06:22:27,687 - root - ERROR - Error al obtener información del módulo payload/cmd/linux/http/mips64/meterpreter_reverse_tcp: 'ModuleManager' object has no attribute 'info'
2025-02-22 06:22:40,910 - MetasploitManager - DEBUG - Error usando msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/mips64/meterpreter_reverse_tcp; exit'' timed out after 10 seconds
2025-02-22 06:23:01,050 - root - ERROR - Error al obtener información del módulo payload/cmd/linux/http/mips64/meterpreter_reverse_tcp: 'ModuleManager' object has no attribute 'info'
2025-02-22 06:26:31,003 - root - INFO - Configuración cargada desde config.yaml.
2025-02-22 06:26:31,003 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 06:26:34,355 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-22 06:26:34,367 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-22 06:26:55,983 - MetasploitManager - DEBUG - Error usando msfconsole: Command 'msfconsole -q -x 'edit payload/cmd/linux/http/mips64/meterpreter_reverse_http; exit'' timed out after 10 seconds
2025-02-22 06:27:16,143 - root - ERROR - Error al obtener información del módulo payload/cmd/linux/http/mips64/meterpreter_reverse_http: 'ModuleManager' object has no attribute 'info'
2025-02-22 06:27:24,228 - MetasploitManager - ERROR - Error obteniendo info del módulo: 'ModuleManager' object has no attribute 'payload'
2025-02-22 06:28:44,876 - root - INFO - Configuración cargada desde config.yaml.
2025-02-22 06:28:44,876 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 06:28:48,486 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-22 06:28:48,493 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-22 06:29:02,743 - MetasploitManager - DEBUG - Error usando msfconsole: Command 'msfconsole -q -x 'edit payload/aix/ppc/shell_find_port; exit'' timed out after 10 seconds
2025-02-22 06:29:22,865 - root - ERROR - Error al obtener información del módulo payload/aix/ppc/shell_find_port: 'ModuleManager' object has no attribute 'info'
2025-02-22 06:45:37,241 - root - INFO - Configuración cargada desde config.yaml.
2025-02-22 06:45:37,242 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 07:00:59,275 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-22 07:00:59,275 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 07:01:19,847 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-22 07:01:19,847 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 07:01:34,727 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-22 07:01:34,727 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 07:02:08,909 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-22 07:02:08,909 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 07:02:39,147 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-22 07:02:39,148 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 07:02:43,805 - MetasploitManager - INFO - Intentando conectar a Metasploit RPC...
2025-02-22 07:02:43,814 - MetasploitManager - INFO - Conectado a Metasploit RPC. Versión: {'version': '6.4.43-dev', 'ruby': '3.1.2 x86_64-linux-gnu 2022-04-12', 'api': '1.0'}
2025-02-22 07:02:59,320 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-22 07:02:59,320 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 07:07:51,852 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-22 07:07:51,852 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 07:09:08,232 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-22 07:09:08,233 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-22 07:11:55,519 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-22 07:11:55,519 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 10:54:01,531 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 10:54:01,532 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 10:54:13,225 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 10:54:13,225 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 10:55:25,987 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 10:55:25,987 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 10:57:48,868 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 10:57:48,868 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:13:44,432 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:13:44,433 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:14:02,859 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:14:02,860 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:14:06,894 - MetasploitWindow - ERROR - Error en monitoreo: 'bool' object is not callable
2025-02-24 11:14:07,880 - MetasploitWindow - ERROR - Error cargando módulos: 'MetasploitConnectionManager' object has no attribute 'list_exploits'
2025-02-24 11:14:11,880 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-24 11:14:11,895 - MetasploitWindow - ERROR - Error en monitoreo: 'bool' object is not callable
2025-02-24 11:14:16,880 - MetasploitWindow - ERROR - Error actualizando sesiones: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-24 11:20:02,493 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:20:02,493 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:20:02,640 - root - WARNING - No se pudo cargar el logo: name 'self' is not defined
2025-02-24 11:26:43,029 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:26:43,030 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:33:16,440 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:33:16,440 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:33:38,921 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:33:38,921 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:40:25,454 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:40:25,454 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:40:25,901 - root - WARNING - Logo de inicio no encontrado en /home/percival/Desktop/VulnHunter/src/ui/assets/logo_inicio.png
2025-02-24 11:45:13,915 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:45:13,915 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:45:14,333 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 11:51:10,251 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:51:10,251 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:51:10,714 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 11:58:41,101 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:58:41,101 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:58:41,537 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 11:59:17,850 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 11:59:17,850 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 11:59:18,289 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 12:10:02,260 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 12:10:02,260 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 12:10:02,669 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 12:14:38,816 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 12:14:38,816 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 12:14:39,242 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 12:21:41,524 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 12:21:41,524 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 12:21:41,958 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 12:22:30,763 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 12:22:30,763 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 12:22:31,194 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 12:25:00,360 - root - INFO - Configuración cargada desde config/config.yaml.
2025-02-24 12:25:00,360 - root - INFO - Nmap está instalado en: /usr/bin/nmap
2025-02-24 12:25:00,789 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 15:29:04,089 - root - INFO - Configuration loaded from config/config.yaml.
2025-02-24 15:29:04,091 - root - INFO - Nmap is installed at: /usr/bin/nmap
2025-02-24 15:29:05,236 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 17:01:51,154 - root - INFO - Configuration loaded from config/config.yaml.
2025-02-24 17:01:51,155 - root - INFO - Nmap is installed at: /usr/bin/nmap
2025-02-24 17:01:52,511 - root - WARNING - Home logo not found at /home/percival/Desktop/VulnHunter/src/ui/assets/logo_home.png
2025-02-24 17:02:07,341 - MetasploitWindow - ERROR - Error in monitoring: 'bool' object is not callable
2025-02-24 17:02:08,323 - MetasploitWindow - ERROR - Error loading modules: 'MetasploitConnectionManager' object has no attribute 'list_exploits'
2025-02-24 17:02:11,658 - MetasploitWindow - ERROR - Error loading modules: 'MetasploitConnectionManager' object has no attribute 'list_exploits'
2025-02-24 17:02:12,323 - MetasploitWindow - ERROR - Error updating sessions: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-24 17:02:12,343 - MetasploitWindow - ERROR - Error in monitoring: 'bool' object is not callable
2025-02-24 17:02:16,629 - MetasploitWindow - ERROR - Error loading modules: 'MetasploitConnectionManager' object has no attribute 'list_exploits'
2025-02-24 17:02:17,175 - MetasploitWindow - ERROR - Error updating sessions: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-24 17:02:17,323 - MetasploitWindow - ERROR - Error updating sessions: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-24 17:02:22,176 - MetasploitWindow - ERROR - Error updating sessions: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-24 17:02:22,325 - MetasploitWindow - ERROR - Error updating sessions: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-24 17:02:27,177 - MetasploitWindow - ERROR - Error updating sessions: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-24 17:02:27,327 - MetasploitWindow - ERROR - Error updating sessions: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-24 17:02:32,177 - MetasploitWindow - ERROR - Error updating sessions: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
2025-02-24 17:02:32,327 - MetasploitWindow - ERROR - Error updating sessions: 'MetasploitConnectionManager' object has no attribute 'get_sessions'
